[project]
name = "Me"
version = "0.1.0"
description = "A ChatGPT-like LLM Chat app for ME"
readme = "README.md"
requires-python = ">=3.10"
authors = [{ name = "Sho Nakatani", email = "lay.sakura@gmail.com" }]
dependencies = [
    "fastapi>=0.115.6",
    "uvicorn>=0.34.0",
]
